const T = {
  cs: {
    nav_home:'Úvod', nav_about:'O nás', nav_dogs:'Naši psi', nav_puppies:'Štěňata',
    nav_litters:'Vrhy', nav_gallery:'Galerie', nav_contact_btn:'Kontaktujte nás',
    footer_nav_title:'Navigace', footer_info_title:'Informace', footer_contact_title:'Kontakt',
    footer_tagline:'Profesionální chovatelská stanice Yorkshire teriérů s FCI registrací. Chováme s láskou od roku 2023.',
    footer_write:'Napište nám', footer_location:'📍 Česká republika',
    footer_fci_reg:'FCI registrace', footer_health:'Zdravotní testy',
    footer_adoption:'Adopční podmínky', footer_faq:'FAQ',
    footer_rights:'© 2026 Great Silkyway. Všechna práva vyhrazena.',
    footer_reg:'Chovatelská stanice s FCI registrací',
    // INDEX
    hero_badge:'🏆 FCI registrovaná stanice',
    hero_title1:'Krásní Yorkshire teriéři',
    hero_title2:'s láskou a péčí',
    hero_desc:'Vítejte v chovatelské stanici Great Silkyway. Chováme Yorkshire teriéry s důrazem na zdraví, povahu a krásu. Každé štěně vyrůstá v rodinném prostředí s láskou a odbornou péčí.',
    hero_btn_puppies:'Dostupná štěňata', hero_btn_about:'Více o nás',
    hero_stat_exp:'Chováme s láskou', hero_stat_families:'Domácí výchova štěňat', hero_stat_reg:'Registrace',
    trust1_title:'Štěňátko vybrané s láskou', trust1_desc:'Každé vyrůstá v naší rodině — ne v kotci',
    trust2_title:'Prověřená kvalita', trust2_desc:'Rodiče s výstavními tituly a zdravím v pořádku',
    trust3_title:'Mezinárodní průkaz původu', trust3_desc:'Garance rodokmenu i celoživotní podpora chovatele',
    feat_fci_title:'FCI průkazy původu', feat_fci_desc:'Všechna štěňata s mezinárodně uznávaným průkazem',
    feat_dna_title:'Zdravé štěňátko', feat_dna_desc:'Vaše štěně přichází zdravé a plné života',
    feat_vac_title:'Očkování & odčervení', feat_vac_desc:'Kompletní veterinární péče před předáním',
    feat_fam_title:'Rodinná výchova', feat_fam_desc:'Štěňata socializována v domácím prostředí',
    about_label:'O chovatelské stanici', about_title:'Chováme yorkshiry s vášní a zodpovědností',
    about_p1:'Chovatelská stanice Great Silkyway vznikla z čisté lásky k Yorkshire teriérům. Chov je pro nás nejen koníčkem, ale posláním — přivést na svět zdravá, dobře socializovaná štěňata, která budou radostí celých rodin.',
    about_p2:'Naši chovatelé jsou registrováni u FCI. Rodiče každého štěněte pečlivě vybíráme podle zdraví, povahy a chovné hodnoty — aby vaše štěňátko přišlo do nového domova jako ten nejlepší možný společník.',
    about_check1:'Registrace FCI', about_check2:'Zdravotní testy rodičů',
    about_check3:'Celoživotní podpora majitelů', about_check4:'Jsme tu pro vás i po předání',
    about_btn:'Zjistit více o nás', badge_exp:'15+ let', badge_breeder:'zkušený chovatel',
    dogs_label:'Chovní jedinci', dogs_title:'Naši chovní psi',
    dogs_subtitle:'Seznamte se s hvězdami naší stanice — chovnými fenami a psy s výbornými výsledky z výstav a zdravotními prověrkami.',
    dogs_show_all:'Zobrazit všechny psy',
    puppies_label:'Aktuální vrh', puppies_title:'Dostupná štěňata',
    puppies_subtitle:'Hledáte svého nového čtyřnohého přítele? Podívejte se na naše aktuálně dostupná štěňata s průkazem FCI.',
    puppies_all:'Všechna štěňata', status_available:'Volné', status_reserved:'Rezervováno', price_on_request:'Na dotaz', gender_female:'Fena', gender_male:'Pes',
    gallery_label:'Fotogalerie', gallery_title:'Naše yorkshire rodina',
    gallery_subtitle:'Krátký pohled do každodenního života naší chovatelské stanice.', gallery_all:'Celá galerie',
    test_label:'Reference', test_title:'Co říkají naše rodiny',
    test_subtitle:'Přečtěte si zkušenosti lidí, kteří si od nás přijali yorkshire teriéra.',
    cta_label:'Máte zájem?', cta_title:'Najděte svého Yorkshire teriéra',
    cta_desc:'Vyplňte krátký dotazník a my vám pomůžeme najít štěně, které bude do vaší rodiny ideálně pasovat.',
    cta_btn1:'Aktuální štěňata', cta_btn2:'Kontaktovat nás',
    // ABOUT
    about_page_title:'O naší chovatelské stanici',
    about_page_desc:'Více než 15 let lásky k Yorkshire teriérům, zodpovědného chovu a šťastných rodin.',
    bc_home:'Úvod', bc_about:'O nás', bc_dogs:'Naši psi', bc_puppies:'Štěňata',
    bc_litters:'Vrhy', bc_gallery:'Galerie', bc_contact:'Kontakt',
    story_label:'Náš příběh', story_title:'Vítejte v Great Silkyway',
    story_p1:'Chovatelská stanice Great Silkyway vznikla v roce 2023 z čisté a nefalšované lásky k Yorkshire teriérům. To, co začalo jako osobní vášeň jedné rodiny, se postupem let rozrostlo v respektovanou chovatelskou stanici s mezinárodní FCI registrací.',
    story_p2:'Naším hlavním posláním je chovat Yorkshire teriéry, kteří jsou nejen krásní navenek, ale především zdraví, dobře socializovaní a s výbornou povahou. Věříme, že správný yorkie je věrný společník pro celou rodinu — od batolat po seniory.',
    story_p3:'Každé štěně, které opouští naši stanici, odchází jako součást naší rodiny. Zůstáváme k dispozici novým majitelům po celý život psa — s radami, podporou i přátelstvím.',
    story_btn1:'Aktuální štěňata', story_btn2:'Napište nám',
    badge_fci:'FCI registrace', badge_since:'od roku 2023',
    values_label:'Naše hodnoty', values_title:'Co nás řídí',
    values_subtitle:'Tyto principy stojí za každým rozhodnutím, které v naší chovatelské stanici činíme.',
    val1_title:'Láska na prvním místě', val1_desc:'Každý náš pes žije jako člen rodiny. Žádné klece, žádná samota — jen domov plný tepla a každodenní péče.',
    val2_title:'Zdraví nade vše', val2_desc:'Naším závazkem je, aby každé štěňátko vyrostlo zdravě a šťastně. Zdraví vašeho budoucího mazlíčka je pro nás na prvním místě.',
    val3_title:'Poctivost a transparentnost', val3_desc:'Sdílíme vše — výsledky zdravotních testů, výstavní tituly i rodokmen. Žádná tajemství.',
    breeder_label:'Chovatelé', breeder_title:'Kdo stojí za Great Silkyway',
    breeder_p1:'Za naší stanicí stojí vášnivá chovatelka se dvěma desetiletími zkušeností s chovem Yorkshire teriérů. Aktivně se účastní výstav psů po celé Evropě a pravidelně absolvuje odborné semináře zaměřené na welfare a zdraví psů.',
    breeder_p2:'Vrhy plánujeme s velkým rozmyslem — vybíráme rodiče nejen podle titulů, ale především podle zdraví, povahy a chovné hodnoty. Počet vrhů za rok záměrně omezujeme, aby každé štěně dostalo tu nejlepší možnou péči a pozornost.',
    breeder_check1:'Členka FCI', breeder_check2:'Aktivní výstavní kariéra v ČR i zahraničí',
    breeder_check3:'Průběžné vzdělávání v oblasti genetiky a welfare', breeder_check4:'Individuální péče o každé štěňátko',
    badge_breeder_year:'Chovatel roku', badge_year:'2022',
    cert_label:'Certifikace & registrace', cert_title:'Naše záruky kvality',
    cert_subtitle:'Transparentnost a profesionalita jsou základem naší práce.',
    cert1_title:'FCI průkaz původu', cert1_desc:'Mezinárodně uznávaný průkaz pro každé štěně',
    cert2_title:'Ověřený původ', cert2_desc:'Transparentní rodokmen s doloženým původem',
    cert3_title:'Veterinární pas', cert3_desc:'Očkování, odčervení, veterinární prohlídka',
    cert4_title:'Celoživotní přátelství', cert4_desc:'Zůstáváme v kontaktu po celý život vašeho mazlíčka',
    about_cta_label:'Pojďme se poznat', about_cta_title:'Máte otázky? Rádi odpovíme.',
    about_cta_desc:'Neváhejte nás kontaktovat. Rádi vám poradíme, zda je yorkshire teriér ta pravá volba pro vás.',
    about_cta_btn1:'Napište nám', about_cta_btn2:'Aktuální štěňata',
    // DOGS PAGE
    dogs_page_title:'Naši chovní jedinci',
    dogs_page_desc:'Šampioni, zdravotně prověření a s výbornou povahou — to jsou rodiče vašeho budoucího mazlíčka.',
    dogs_intro_label:'Výběr rodičů', dogs_intro_title:'Základ dobrého vrhu',
    dogs_intro_subtitle:'Chovné feny a psi jsou srdcem každé chovatelské stanice. U nás procházejí každý rok komplexním zdravotním vyšetřením a jsou aktivními výstavními psy s výbornými výsledky.',
    females_label:'Chovné feny', females_title:'Naše dámy',
    males_label:'Chovní psi', males_title:'Naši pánové',
    breed_yt:'Yorkshire teriér', dna_clean:'V pořádku ✓',
    dog_born_f:'Narozena', dog_born_m:'Narozen', dog_litters:'Vrhy', dog_dna:'Zdraví',
    dog_titles:'Tituly', dog_offspring:'Potomci',
    senorita_desc:'Nádherná fena s výjimečně hedvábnou srstí a typickým výstavním výrazem. Senorita je elegantní, temperamentní a plná energie.',
    michelle_desc:'Okouzlující fena s nádhernou srstí a výraznou osobností. Michelle je elegantní, klidná a do každého vrhu předává ty nejlepší vlastnosti.',
    matteo_desc:'Výjimečný pes s titulem Junior Champion. Matteo disponuje dokonalou stavbou těla, nádhernou srstí a sebevědomou povahou výstavního psa nejvyšší kvality.',
    oxygen_desc:'Elegantní fena s výjimečnou povahou a nádhernou srstí. Oxygen Fresh Stream je klidná, laskavá a svým potomkům předává ty nejlepší vlastnosti.',
    health_label:'Proč si vybrat Great Silkyway', health_title:'Co získáte s naším štěňátkem',
    health_desc:'Každé štěňátko z naší stanice přichází s něčím víc, než jen průkazem:',
    health1_title:'Vitální a šťastné', health1_desc:'Štěňátko odchází zdravé, plné energie a připravené na nový domov',
    health2_title:'Socializace od prvního dne', health2_desc:'Vyrůstá v rodině, ne v kleci — přizpůsobí se rychle a bez stresu',
    health3_title:'Ověřený rodokmen', health3_desc:'Znáte celou rodinnou historii svého psa — transparentně a s láskou',
    health4_title:'Podpora bez hranic', health4_desc:'S jakýmkoli dotazem se na nás obraťte kdykoli — jsme tu celý život',
    dogs_cta_label:'Plánované vrhy', dogs_cta_title:'Zajímá vás některý z vrhů?',
    dogs_cta_desc:'Napište nám a my vám sdělíme aktuální plány pro příští vrhy i možnosti rezervace.',
    dogs_cta_btn1:'Napište nám', dogs_cta_btn2:'Dostupná štěňata',
    // PUPPIES PAGE
    puppies_page_title:'Naše štěňátka',
    puppies_page_desc:'Každé štěňátko vyrůstá v naší rodině — s láskou, péčí a přirozenou socializací od prvního dne.',
    adoption_label:'Jak to funguje', adoption_title:'Jak probíhá adopce štěněte',
    adoption_desc:'Záleží nám na tom, aby každé štěně odešlo do správné rodiny. Proto naši adopci pojímáme jako vzájemné poznávání — chceme vědět, co nový majitel čeká, a on by měl vědět vše o nás.',
    step1_title:'Kontaktujte nás', step1_desc:'Napište nám e-mail nebo zavolejte. Rádi odpovíme na všechny vaše otázky a zjistíme, zda máme vhodné štěně pro vás.',
    step2_title:'Přijďte se podívat', step2_desc:'Rádi vás přivítáme osobně, ukážeme vám naše štěňátka i prostředí, ve kterém vyrůstají. Žádný spěch — jen přirozené seznámení.',
    step3_title:'Průběžné fotky a video', step3_desc:'Budete pravidelně dostávat fotografie a videa vašeho štěněte. Sledujete jeho vývoj od prvního dne.',
    step4_title:'Nový začátek', step4_desc:'Ve chvíli, kdy je štěňátko připraveno, odchází s plnou péčí do své nové rodiny. Jsme vám k dispozici i nadále — s radami, odpověďmi i přátelstvím.',
    included_title:'S čím štěňátko odchází do nového domova', included_desc:'Chceme, aby štěňátko i jeho nová rodina měli ten nejlepší začátek společně:',
    inc1:'FCI průkaz původu', inc2:'Veterinární pas EU', inc3:'Kompletní očkování',
    inc4:'Odčervení', inc5:'Mikročip', inc6:'Potvrzení o zdravotním stavu',
    inc7:'Kupní smlouva', inc7_new:'Kupní smlouva', inc8:'Balíček péče', inc8_new:'Balíček péče', inc9:'Celoživotní podpora chovatele', inc_btn:'Napište nám',
    litter_label:'Vrh C', litter_title:'Naše štěňátka hledají domov',
    litter_desc:'Každé štěňátko vyrůstá v rodinném prostředí s láskou a individuální péčí.',
    price_inquiry:'Cena na dotaz', price_reserved_lbl:'Rezervováno',
    btn_interested:'Mám zájem', btn_taken:'Obsazeno',
    planned_label:'Plánované vrhy', planned_title:'Připravované vrhy 2025',
    planned_subtitle:'Zapište se do pořadníku a my vás kontaktujeme jako první, jakmile budou štěňata k dispozici.',
    plan1_label:'Plánovaný vrh · jaro 2025', plan1_title:'Luna × Maxim',
    plan1_desc:'Kombinace dvou výjimečných jedinců. Očekáváme 2–4 štěňata s vynikající genetikou a zlatavou srstí.',
    plan2_label:'Plánovaný vrh · podzim 2025', plan2_title:'Stella × Duke',
    plan2_desc:'Duke a Stella jsou skvělý pár — jejich potomci mají vždy výborný typ a nádhernou srst.',
    plan3_label:'Upřesňujeme · konec 2025', plan3_title:'Třetí vrh',
    plan3_desc:'Třetí vrh roku plánujeme. Detaily upřesníme brzy. Zapište se do pořadníku a dostanete info jako první.',
    waitlist_btn:'Zapsat do pořadníku',
    puppies_cta_label:'Začněte hned', puppies_cta_title:'Připraveni přivítat yorkshire teriéra?',
    puppies_cta_desc:'Kontaktujte nás a společně najdeme to pravé štěně pro vaši rodinu.',
    puppies_cta_btn1:'Kontaktovat nás', puppies_cta_btn2:'Více o nás',
    // LITTERS PAGE
    litters_page_title:'Naše vrhy', litters_page_desc:'Přehled uskutečněných a aktuálních vrhů naší chovatelské stanice.',
    litters_label:'Přehled vrhů', litters_title:'Vrhy Great Silkyway',
    litter_a_title:'Vrh A', litter_a_desc:'Štěňata z vrhu A naší chovatelské stanice.',
    litter_b_title:'Vrh B', litter_b_desc:'Štěňata z vrhu B naší chovatelské stanice.',
    litter_c_title:'Vrh C', litter_c_desc:'Štěňata z vrhu C naší chovatelské stanice.',
    litter_inquiry:'Dotaz na vrh', litter_status_available:'Dostupný', litter_status_unavailable:'Nedostupné',
    vrhy_cta_label:'Plánované vrhy', vrhy_cta_title:'Zajímá vás některý z vrhů?',
    vrhy_cta_desc:'Napište nám a my vám sdělíme aktuální plány pro příští vrhy i možnosti rezervace.',
    vrhy_cta_btn1:'Napište nám', vrhy_cta_btn2:'Dostupná štěňata',
    // GALLERY PAGE
    gallery_page_title:'Fotogalerie', gallery_page_desc:'Nahlédněte do každodenního života naší chovatelské stanice, výstav a rodinného štěstí.',
    filter_all:'Vše', filter_puppies:'Štěňata', filter_dogs:'Dospělí psi', filter_shows:'Výstavy', filter_families:'Šťastné rodiny',
    gallery_cta_label:'Sdílejte radost', gallery_cta_title:'Máte yorkshire od nás? Pošlete nám fotky!',
    gallery_cta_desc:'Rádi přidáme fotky vašeho mazlíčka do naší galerie šťastných rodin.', gallery_cta_btn:'Napsat nám',
    // CONTACT PAGE
    contact_page_title:'Kontaktujte nás', contact_page_desc:'Máte otázky ohledně štěňat, plánovaných vrhů nebo chovu? Napište nám — rádi odpovíme.',
    contact_label:'Spojte se s námi', contact_title:'Jsme tu pro vás',
    contact_desc:'Neváhejte nás kontaktovat s jakýmkoliv dotazem. Obvykle odpovídáme do 24 hodin. Rádi si povídáme o yorkshire teriérech — to je naše velká vášeň!',
    contact_email_label:'E-mail', contact_phone_label:'Telefon / WhatsApp',
    contact_location_label:'Umístění', contact_location_val:'Česká republika',
    contact_hours_label:'Odpovídáme', contact_hours_val:'Po–Pá · 9:00 – 19:00',
    contact_follow:'Sledujte nás', faq_title:'Časté dotazy',
    faq1_q:'Ve kolika týdnech štěňata předáváte?', faq1_a:'Štěňata předáváme v 10 týdnech věku, kdy jsou plně socializovaná a schopná opustit matku.',
    faq2_q:'Jaká je záloha pro rezervaci?', faq2_a:'Rezervační záloha je 5 000 Kč, která se odečítá z konečné ceny štěněte.',
    faq3_q:'Zasíláte štěňata do zahraničí?', faq3_a:'Ano, zkušenosti máme s vývozem do celé EU. Štěňata cestují s EU pasem a splňují všechny požadavky.',
    form_title:'Napište nám zprávu', form_desc:'Vyplňte formulář a ozveme se vám co nejdříve.',
    form_firstname:'Jméno *', form_lastname:'Příjmení *', form_email_lbl:'E-mailová adresa *', form_phone_lbl:'Telefon',
    form_subject_lbl:'Téma zprávy', form_subject_opt0:'Vyberte téma…', form_subject_opt1:'Zájem o štěně',
    form_subject_opt2:'Rezervace — pořadník', form_subject_opt3:'Obecné informace',
    form_subject_opt4:'Zdravotní dotazy', form_subject_opt5:'Jiné',
    form_message_lbl:'Zpráva *',
    form_gdpr:'Souhlasím se zpracováním osobních údajů pro účely odpovědi na můj dotaz. *',
    form_submit:'Odeslat zprávu', form_success_title:'Zpráva odeslána!',
    form_success_desc:'Děkujeme za váš zájem. Ozveme se vám do 24 hodin.',
  },
  en: {
    nav_home:'Home', nav_about:'About us', nav_dogs:'Our Dogs', nav_puppies:'Puppies',
    nav_litters:'Litters', nav_gallery:'Gallery', nav_contact_btn:'Contact us',
    footer_nav_title:'Navigation', footer_info_title:'Information', footer_contact_title:'Contact',
    footer_tagline:'Professional Yorkshire Terrier kennel with FCI registration. Breeding with love since 2023.',
    footer_write:'Write to us', footer_location:'📍 Czech Republic',
    footer_fci_reg:'FCI Registration', footer_health:'Health Tests',
    footer_adoption:'Adoption Terms', footer_faq:'FAQ',
    footer_rights:'© 2026 Great Silkyway. All rights reserved.',
    footer_reg:'FCI Registered Kennel',
    hero_badge:'🏆 FCI registered kennel',
    hero_title1:'Beautiful Yorkshire Terriers',
    hero_title2:'with love and care',
    hero_desc:'Welcome to the Great Silkyway kennel. We breed Yorkshire Terriers with a focus on health, temperament and beauty. Every puppy grows up in a family environment with love and professional care.',
    hero_btn_puppies:'Available puppies', hero_btn_about:'Learn more',
    hero_stat_exp:'Bred with love', hero_stat_families:'Home-raised puppies', hero_stat_reg:'Registration',
    trust1_title:'A puppy chosen with love', trust1_desc:'Each one grows up in our family — not in a kennel',
    trust2_title:'Proven quality', trust2_desc:'Parents with show titles and verified health',
    trust3_title:'International pedigree', trust3_desc:'Guaranteed lineage and lifelong breeder support',
    feat_fci_title:'FCI Pedigrees', feat_fci_desc:'All puppies with internationally recognised pedigree',
    feat_dna_title:'Healthy puppy', feat_dna_desc:'Your puppy arrives healthy and full of life',
    feat_vac_title:'Vaccination & Deworming', feat_vac_desc:'Full veterinary care before handover',
    feat_fam_title:'Family Upbringing', feat_fam_desc:'Puppies socialised in a home environment',
    about_label:'About the kennel', about_title:'We breed Yorkies with passion and responsibility',
    about_p1:'The Great Silkyway kennel was born out of pure love for Yorkshire Terriers. Breeding is not just a hobby for us, but a mission — to bring healthy, well-socialised puppies into the world that will be a joy to entire families.',
    about_p2:'Our breeders are registered with FCI. We carefully select the parents of every puppy based on health, temperament and breeding value — so your puppy arrives as the very best companion it can be.',
    about_check1:'FCI Registration', about_check2:'Health tests of parents',
    about_check3:'Lifetime support for owners', about_check4:'We are here for you even after handover',
    about_btn:'Learn more about us', badge_exp:'15+ years', badge_breeder:'experienced breeder',
    dogs_label:'Breeding dogs', dogs_title:'Our breeding dogs',
    dogs_subtitle:'Meet the stars of our kennel — breeding females and males with excellent show results and health screenings.',
    dogs_show_all:'View all dogs',
    puppies_label:'Current litter', puppies_title:'Available puppies',
    puppies_subtitle:'Looking for your new four-legged friend? Check out our currently available puppies with FCI pedigrees.',
    puppies_all:'All puppies', status_available:'Available', status_reserved:'Reserved', price_on_request:'On request', gender_female:'Female', gender_male:'Male',
    gallery_label:'Photo gallery', gallery_title:'Our Yorkshire family',
    gallery_subtitle:'A brief glimpse into the everyday life of our kennel.', gallery_all:'Full gallery',
    test_label:'Testimonials', test_title:'What our families say',
    test_subtitle:'Read the experiences of people who adopted a Yorkshire Terrier from us.',
    cta_label:'Interested?', cta_title:'Find your Yorkshire Terrier',
    cta_desc:'Fill out a short questionnaire and we will help you find a puppy that will be a perfect fit for your family.',
    cta_btn1:'Current puppies', cta_btn2:'Contact us',
    about_page_title:'About our kennel',
    about_page_desc:'Over 15 years of love for Yorkshire Terriers, responsible breeding and happy families.',
    bc_home:'Home', bc_about:'About us', bc_dogs:'Our Dogs', bc_puppies:'Puppies',
    bc_litters:'Litters', bc_gallery:'Gallery', bc_contact:'Contact',
    story_label:'Our story', story_title:'Welcome to Great Silkyway',
    story_p1:'The Great Silkyway kennel was founded in 2023 out of genuine love for Yorkshire Terriers. What started as a personal passion of one family has grown over the years into a respected kennel with international FCI registration.',
    story_p2:'Our main mission is to breed Yorkshire Terriers who are not only beautiful on the outside, but above all healthy, well-socialised and with an excellent temperament. We believe the right Yorkie is a faithful companion for the whole family — from toddlers to seniors.',
    story_p3:'Every puppy that leaves our kennel goes as a part of our family. We remain available to new owners for the entire life of the dog — with advice, support and friendship.',
    story_btn1:'Current puppies', story_btn2:'Write to us',
    badge_fci:'FCI registration', badge_since:'since 2023',
    values_label:'Our values', values_title:'What drives us',
    values_subtitle:'These principles underpin every decision we make at our kennel.',
    val1_title:'Love first', val1_desc:'Every dog lives as a member of our family. No cages, no loneliness — just a home full of warmth and daily care.',
    val2_title:'Health above all', val2_desc:'Our commitment is for every puppy to grow up healthy and happy. The health of your future companion is our top priority.',
    val3_title:'Honesty and transparency', val3_desc:'We share everything — health test results, show titles and pedigree. No secrets.',
    breeder_label:'Breeders', breeder_title:'Who is behind Great Silkyway',
    breeder_p1:'Our kennel is run by a passionate breeder with two decades of experience in Yorkshire Terrier breeding. She actively participates in dog shows across Europe and regularly attends professional seminars focused on animal welfare and health.',
    breeder_p2:'We plan litters with great care — we select parents not only by titles, but above all by health, temperament and breeding value. We deliberately limit the number of litters per year so that every puppy receives the best possible care and attention.',
    breeder_check1:'Member of FCI', breeder_check2:'Active show career in Czech Republic and abroad',
    breeder_check3:'Ongoing education in genetics and animal welfare', breeder_check4:'Individual care for every puppy',
    badge_breeder_year:'Breeder of the Year', badge_year:'2022',
    cert_label:'Certifications & registrations', cert_title:'Our quality guarantees',
    cert_subtitle:'Transparency and professionalism are the foundation of our work.',
    cert1_title:'FCI Pedigree', cert1_desc:'Internationally recognised pedigree for every puppy',
    cert2_title:'Verified origin', cert2_desc:'Transparent pedigree with documented ancestry',
    cert3_title:'Veterinary Passport', cert3_desc:'Vaccination, deworming, veterinary examination',
    cert4_title:'Lifelong friendship', cert4_desc:'We stay in touch throughout your dog\'s whole life',
    about_cta_label:"Let's get acquainted", about_cta_title:"Have questions? We're happy to answer.",
    about_cta_desc:'Do not hesitate to contact us. We will be happy to advise you whether a Yorkshire Terrier is the right choice for you.',
    about_cta_btn1:'Write to us', about_cta_btn2:'Current puppies',
    dogs_page_title:'Our breeding dogs',
    dogs_page_desc:'Champions, health-screened and with excellent temperament — these are the parents of your future companion.',
    dogs_intro_label:'Choice of parents', dogs_intro_title:'Foundation of a good litter',
    dogs_intro_subtitle:'Breeding females and males are the heart of every kennel. Ours undergo comprehensive health examinations every year and are active show dogs with excellent results.',
    females_label:'Breeding females', females_title:'Our ladies',
    males_label:'Breeding males', males_title:'Our gentlemen',
    breed_yt:'Yorkshire Terrier', dna_clean:'All clear ✓',
    dog_born_f:'Born', dog_born_m:'Born', dog_litters:'Litters', dog_dna:'Health',
    dog_titles:'Titles', dog_offspring:'Offspring',
    senorita_desc:'Beautiful female with exceptionally silky coat and typical show expression. Senorita is elegant, spirited and full of energy.',
    michelle_desc:'Enchanting female with a beautiful coat and strong personality. Michelle is elegant, calm and passes on the very best qualities in every litter.',
    matteo_desc:'Exceptional male with the title of Junior Champion. Matteo has a perfect body structure, a beautiful coat and the confident personality of a top-quality show dog.',
    health_label:'Why choose Great Silkyway', health_title:'What you get with our puppy',
    health_desc:'Every puppy from our kennel comes with something more than just a pedigree:',
    health1_title:'Vital and happy', health1_desc:'Your puppy leaves healthy, full of energy and ready for its new home',
    health2_title:'Socialised from day one', health2_desc:'Raised in a family, not a cage — adapts quickly and without stress',
    health3_title:'Verified pedigree', health3_desc:'You know the full family history of your dog — transparently and with love',
    health4_title:'Support without limits', health4_desc:'Reach out with any question at any time — we are here for life',
    dogs_cta_label:'Planned litters', dogs_cta_title:'Interested in a litter?',
    dogs_cta_desc:'Write to us and we will share the current plans for upcoming litters and reservation options.',
    dogs_cta_btn1:'Write to us', dogs_cta_btn2:'Available puppies',
    puppies_page_title:'Available puppies',
    puppies_page_desc:'All puppies leave with an FCI pedigree, vaccination, deworming and a veterinary passport.',
    adoption_label:'How it works', adoption_title:'How adoption works',
    adoption_desc:'It is important to us that every puppy goes to the right family. We treat adoption as a mutual introduction — we want to know what the new owner expects, and they should know everything about us.',
    step1_title:'Contact us', step1_desc:'Write to us or call. We will happily answer all your questions and find out if we have the right puppy for you.',
    step2_title:'Come and visit', step2_desc:'We would love to welcome you in person, show you our puppies and the home they grow up in. No rush — just a natural getting-to-know-each-other.',
    step3_title:'Regular photos and video', step3_desc:'You will regularly receive photos and videos of your puppy. You can watch its development from day one.',
    step4_title:'A new beginning', step4_desc:'When the puppy is ready, it goes to its new family with full care. We remain available to you — with advice, answers and friendship.',
    included_title:'What your puppy takes home', included_desc:'We want every puppy and their new family to have the very best start together:',
    inc1:'FCI Pedigree', inc2:'EU Veterinary passport', inc3:'Full vaccination',
    inc4:'Deworming', inc5:'Microchip', inc6:'Health certificate',
    inc7:'Purchase contract', inc7_new:'Purchase contract', inc8:'Care pack', inc8_new:'Care pack', inc9:'Lifetime breeder support', inc_btn:'Write to us',
    litter_label:'Litter C', litter_title:'Our puppies looking for a home',
    litter_desc:'Each puppy grows up in a family environment with love and individual care.',
    price_inquiry:'Price on request', price_reserved_lbl:'Reserved',
    btn_interested:"I'm interested", btn_taken:'Taken',
    planned_label:'Planned litters', planned_title:'Upcoming litters 2025',
    planned_subtitle:'Join the waiting list and we will contact you first as soon as puppies become available.',
    plan1_label:'Planned litter · Spring 2025', plan1_title:'Luna × Maxim',
    plan1_desc:'A combination of two exceptional individuals. We expect 2–4 puppies with outstanding genetics and a golden coat.',
    plan2_label:'Planned litter · Autumn 2025', plan2_title:'Stella × Duke',
    plan2_desc:'Duke and Stella are a great pair — their offspring always have excellent type and a beautiful coat.',
    plan3_label:'To be confirmed · end of 2025', plan3_title:'Third litter',
    plan3_desc:'We are planning a third litter this year. Details to follow soon. Join the waiting list and be the first to know.',
    waitlist_btn:'Join waiting list',
    puppies_cta_label:'Get started', puppies_cta_title:'Ready to welcome a Yorkshire Terrier?',
    puppies_cta_desc:'Contact us and together we will find the perfect puppy for your family.',
    puppies_cta_btn1:'Contact us', puppies_cta_btn2:'More about us',
    litters_page_title:'Our litters', litters_page_desc:'Overview of past and current litters from our kennel.',
    litters_label:'Litter overview', litters_title:'Great Silkyway litters',
    litter_a_title:'Litter A', litter_a_desc:'Puppies from litter A of our kennel.',
    litter_b_title:'Litter B', litter_b_desc:'Puppies from litter B of our kennel.',
    litter_c_title:'Litter C', litter_c_desc:'Puppies from litter C of our kennel.',
    litter_inquiry:'Enquire about litter', litter_status_available:'Available', litter_status_unavailable:'Unavailable',
    vrhy_cta_label:'Planned litters', vrhy_cta_title:'Interested in a litter?',
    vrhy_cta_desc:'Write to us and we will share the current plans for upcoming litters and reservation options.',
    vrhy_cta_btn1:'Write to us', vrhy_cta_btn2:'Available puppies',
    gallery_page_title:'Photo Gallery', gallery_page_desc:'A glimpse into the everyday life of our kennel, shows and family happiness.',
    filter_all:'All', filter_puppies:'Puppies', filter_dogs:'Adult dogs', filter_shows:'Shows', filter_families:'Happy families',
    gallery_cta_label:'Share the joy', gallery_cta_title:'Have a Yorkie from us? Send us photos!',
    gallery_cta_desc:'We would love to add photos of your pet to our gallery of happy families.', gallery_cta_btn:'Write to us',
    contact_page_title:'Contact us', contact_page_desc:'Have questions about puppies, planned litters or breeding? Write to us — we will be happy to answer.',
    contact_label:'Get in touch', contact_title:"We're here for you",
    contact_desc:'Do not hesitate to contact us with any question. We usually respond within 24 hours. We love talking about Yorkshire Terriers — it is our great passion!',
    contact_email_label:'E-mail', contact_phone_label:'Phone / WhatsApp',
    contact_location_label:'Location', contact_location_val:'Czech Republic',
    contact_hours_label:'We respond', contact_hours_val:'Mon–Fri · 9:00 – 19:00',
    contact_follow:'Follow us', faq_title:'Frequently asked questions',
    faq1_q:'At how many weeks do you hand over puppies?', faq1_a:'We hand over puppies at 10 weeks of age, when they are fully socialised and ready to leave their mother.',
    faq2_q:'What is the reservation deposit?', faq2_a:'The reservation deposit is 5 000 CZK, which is deducted from the final price of the puppy.',
    faq3_q:'Do you ship puppies abroad?', faq3_a:'Yes, we have experience exporting to the entire EU. Puppies travel with an EU passport and meet all requirements.',
    form_title:'Send us a message', form_desc:'Fill in the form and we will get back to you as soon as possible.',
    form_firstname:'First name *', form_lastname:'Last name *', form_email_lbl:'Email address *', form_phone_lbl:'Phone',
    form_subject_lbl:'Subject', form_subject_opt0:'Select a topic…', form_subject_opt1:'Interest in a puppy',
    form_subject_opt2:'Reservation — waiting list', form_subject_opt3:'General information',
    form_subject_opt4:'Health queries', form_subject_opt5:'Other',
    form_message_lbl:'Message *',
    form_gdpr:'I consent to the processing of my personal data for the purpose of responding to my enquiry. *',
    form_submit:'Send message', form_success_title:'Message sent!',
    form_success_desc:'Thank you for your interest. We will get back to you within 24 hours.',
  }
};

function getLang() { return localStorage.getItem('gs_lang') || 'cs'; }

function setLang(lang) {
  localStorage.setItem('gs_lang', lang);
  document.documentElement.lang = lang;
  applyTranslations(lang);
  updateSwitcher(lang);
}

function toggleLang() { setLang(getLang() === 'cs' ? 'en' : 'cs'); }

function applyTranslations(lang) {
  const t = T[lang];
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const k = el.getAttribute('data-i18n');
    if (t[k] !== undefined) el.textContent = t[k];
  });
  document.querySelectorAll('[data-i18n-placeholder]').forEach(el => {
    const k = el.getAttribute('data-i18n-placeholder');
    if (t[k] !== undefined) el.placeholder = t[k];
  });
}

function updateSwitcher(lang) {
  document.querySelectorAll('.lang-switcher').forEach(btn => {
    btn.textContent = lang === 'cs' ? 'EN' : 'CZ';
    btn.setAttribute('aria-label', lang === 'cs' ? 'Switch to English' : 'Přepnout do češtiny');
  });
}

document.addEventListener('DOMContentLoaded', () => {
  const lang = getLang();
  document.documentElement.lang = lang;
  applyTranslations(lang);
  updateSwitcher(lang);
});
